name: PragmaticIdeals
favicon: null
layout_spectrum: 0.8307113572955132
typography_spectrum: 0.6106202164664865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9257234944961965
  lightness: 0.8557325033470988
  saturation: 0.9785893536172807
  rhythmicContrast: 0.769910937640816
purpose: []
